server:
  port: 8080
eureka:
  instance:
    hostname: com.eureka.server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
